INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (1, N'Иванов         ', N'Luka           ', N'Андреевич      ', 20, 4, 1, 1)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (2, N'Петров         ', N'Семен          ', N'Евгеньевич     ', 21, 2, 3, 2)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (3, N'Лавриков       ', N'Олег           ', N' Петрович      ', 22, 3, 2, 3)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (4, N'Кучкин         ', N'Захар          ', N'Леонидович     ', 23, 5, 1, 1)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (5, N'Лапин          ', N'Сергей         ', N'Михайлович     ', 21, 1, 4, 3)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (6, N'Кочубей        ', N'Егор           ', N'Николевич      ', 22, 4, 5, 2)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (7, N'Бурый          ', N'Игнат          ', N'Валиахметович  ', 23, 2, 1, 1)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (8, N'Трухин         ', N'Павел          ', N'Геннадьевич    ', 25, 5, 1, 1)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (9, N'Лужков         ', N'Семен          ', N'Семенович      ', 24, 3, 4, 3)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (10, N'Калесо         ', N'Андрей         ', N'Александрович  ', 29, 4, 3, 2)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (11, N'Кукуруза       ', N'Александр      ', N'Семенович      ', 31, 1, 1, 1)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (12, N'Магнатов       ', N'Али            ', N'Магамедович    ', 42, 5, 2, 3)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (13, N'Иракли         ', N'Юсуф           ', N'               ', 21, 5, 5, 2)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (14, N'Каримов        ', N'Рашид          ', N'Иосифович      ', 22, 3, 1, 1)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (15, N'Барамзина      ', N'Эделаида       ', N'Каштановна     ', 23, 2, 4, 3)
INSERT INTO [dbo].[Students] ([Id], [Surname], [Name], [Patronymic], [Age], [Rating], [FacultyId], [UniversityId]) VALUES (16, N'Унаги          ', N'Марина         ', N'Андреевна      ', 25, 4, 1, 1)
